language:
  - python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      script:
        - set -e  # If any of the following steps fail, just stop at that point.
        - make -C docs html  # Build the documentation.
        - pip3 install doctr
        - doctr deploy . --built-docs docs/build/html/  # Publish the documentation.
    - name: "Python 3.6.0 on Xenial Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
      # https://blog.travis-ci.com/2018-10-11-windows-early-release
    - name: "Python 3.7.5 on macOS, xcode11.2"
      os: osx
      osx_image: xcode11.2  # Python 3.7.5 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      before_install:
        python3 --version ; pip3 --version ; sw_vers
    - name: "Python 3.7.5 on macOS, xcode10"
      os: osx
      osx_image: xcode10  # Python 3.7.4 running on macOS 10.13.6
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      before_install:
        python3 --version ; pip3 --version ; sw_vers
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      # python: 3.7         # 'python:' is ignored on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      # python: 3.7         # 'python:' is ignored on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  # Install this package and the packages listed in requirements.txt.
  - pip3 install --upgrade pip
  - pip3 install . #pip install --upgrade pip
  # Install extra requirements for running tests and building docs.
  - pip3 install -r requirements-dev.txt
script:
  - set -e  # If any of the following steps fail, just stop at that point.
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
#  - python3 platform-info.py || python platform-info.py

notifications:
  email: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

env:
  global:
    # Doctr deploy key for vstadnytskyi/auxiliary
    - secure: "C4gl2WeahqYWTRgpTWmFalz+u/3mBSryz/Bx3+1g3wSjuqY4mhGYKXHcYFDRYId2TEem4rRcggDFuje868mU2gr5vaEi2e8JWP6h7Z7+SqCCGIv+N5ttI+d4ETINmmFyLDswCCCnfzz0tLI+Ja/3NIOz3U6PAu27Yb9Nky3KAI91V02nQa7Yu2Ad+U5Euu8Dv+yH/XkAu/BoFzHrZmDcyUmVyoju1gEe0D1R+q+ospsJ7/bJpOcKQTuf6KO0MvqWmSIHlLKxl+wsRbFAlBv6XfZyLV449U/zcAlx0RCJbzzMuTJ6LtiV1yPmiGXdfRxtyT2KPSCGjAKfSk3X4cVqVwB7QOmE/CEr7pqhcLYdgVcd60BBzzQ6MOsOsvBWPdphZwFrrGrD3eVLVcEjeNhCbLEovUkVnaHPhwDrl9pFS1ip3QjI3DsE+fIDc34/MbdMuvrf5dQW/V7esqVEC0uXSTiLO8KwN8hd0Tq/kOwoxMF2xq/02EjGH3GpKoFgEBDmIROCjiPcCWYLWV9VuiIAhXrSR1tgqoHyIhlyQAH07ZZgEpuOHtUrEckG2MQfGpW9cKFOPV0k/6IjmMeNFOGyhrCoVtyXYWOayi+IUce8p17F15ew+Sw50HR3KJC1Laeaaw9nOSZ25NdTK4MxpmOLbxXXTOU8AE/4+vW2SJ6jcjE="
